// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System;

namespace Bangumi.Data.Models
{

    public class Site
    {

        /// <summary>
        /// Examples: "bangumi", "iqiyi", "nicovideo", "bilibili", "pptv"
        /// </summary>
        [JsonProperty("site")]
        public string SiteName { get; set; }

        /// <summary>
        /// Examples: "213759", "a_19rrhb12tt", "40379", "41983", "kyojin-no-hoshi"
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// Examples: "2015-10-29T08:31:41Z", "2012-12-24T06:00:00Z", "1969-10-04T16:00:00Z", "1969-10-04T16:00:01Z", "2016-12-05T06:24:50Z"
        /// </summary>
        [JsonProperty("begin")]
        public DateTimeOffset? Begin { get; set; }

        /// <summary>
        /// Examples: "", "港区可见", "分割为 TV 放送", "原始版本为剧场版但是 Netflix 目前将其做成 14 集 TV 分割形式放送"
        /// </summary>
        [JsonProperty("comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Examples: "http://www.iqiyi.com/dongman/20130715/839f4bf2c2cbe419.html", "http://www.iqiyi.com/dongman/20130715/d7a321d48f825733.html", "http://www.iqiyi.com/v_19rrifx03h.html", "http://www.iqiyi.com/v_19rrifx03f.html", "http://www.iqiyi.com/dongman/20130715/75c20dc1fe211093.html"
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }

        public Site Clone() => new Site
        {
            SiteName = SiteName,
            Id = Id,
            Begin = Begin,
            Comment = Comment,
            Url = Url
        };
    }

}
